name: Build

on:
  push:
    branches:
      - main
    paths:
      - "**.cpp"
      - "**.h"
      - "**.java"

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  WEBRTC_CACHE_BRANCH: 7339
  WEBRTC_CHECKOUT_FOLDER: webrtc
  WEBRTC_INSTALL_FOLDER: webrtc/build

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux_x86-64
            runs-on: ubuntu-22.04
        java: [17]
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - id: prepare
        name: Prepare build
        uses: ./.github/actions/prepare-linux

      - id: maven-build
        name: Maven build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java }}
          platform-name: ${{ matrix.platform.name }}
